# Default values for gorego.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: ghcr.io/colinrgodsey/buildfarm-worker
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

statefulset:
  enabled: true

service:
  type: ClusterIP
  port: 9092

probes:
  liveness:
    initialDelaySeconds: 3
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 3
  readiness:
    initialDelaySeconds: 1
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 3

storage:
  # If empty, default storage class will be used.
  className: ""
  size: 10Gi

config:
  listen_addr: ":50051"
  local_cache_dir: "/tmp/cache"
  local_cache_max_size_gb: 10
  log_level: "info"
  backing_cache:
    target: ""
  telemetry:
    metrics_addr: ":9090"
    tracing_endpoint: ""
  execution:
    enabled: true
    concurrency: 0
    build_root: "/tmp/build"
    queue_size: 1000
    sandbox:
      enabled: true
      binary_path: "/bin/linux-sandbox"
      network_isolation: true
      writable_paths: []
      kill_delay: 5
      debug: false
